# Generated by Django 4.0.5 on 2022-07-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_seller_id_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
